### ISSUE TITLE
How import the project? 

### ISSUE THREAD

**Issue by jmarin0802** [Apress/pivotal-certified-pro-spring-dev-exam-02#22]
Hi, I have a problem, i try to import the project pivotal-certified-pro-spring-dev-exam-02, but I can find the solutions, what's happen here? help me please, i try to import the project in eclipse IDE and vscode but in anyone it don't working

all errors are similar in each of the classes and modules
![errores](https://user-images.githubusercontent.com/58563151/109232216-b4692c00-77a6-11eb-8219-3a27e5f990a7.jpg)

do I need something else?
![mipc](https://user-images.githubusercontent.com/58563151/109232867-b7185100-77a7-11eb-8fbc-dceedc625ca2.jpg)

**Comment by iuliana** [comment]
Hello @jmarin0802 , 

I am so sorry for seeing this issue so late.  I use the same account for work and I think the notification got lost amon the work related ones. 

As for the problems you are seeing, check IntelliJ IDEA setup and make sure it sets the Project SDK and Project language level to 11. Newer versions of IntelliJ IDEA set those to the most recent JDK version, so that might cause the issue depicted here, since the project does not build with versions > 11.

If you manage to build the project with Gradle from the command line, then the editor setup is to blame. 

Cheers, 
Iuliana
